### ISSUE TITLE
Redbear ble shield

### ISSUE THREAD

**Issue by jacobrosenthal** [guanix/arduino-nrf8001#2]
Have you attempted to use this with the RedBear shield?
redbearlab.com

From looking through your code, your implementation is far more easy to read than theirs, 

They don't release their schematic, but I believe they don't use a reset pin, have reqn on 9 and rdy on 8.

Sadly it doesn't get past trying to talk to the chip  "Calling transmitReceive..." so I'm still missing something.

**Comment by guanix** [comment]
They actually sent me a free shield to test. There is some strange level shifting circuity on their board, and possibly other components on the reset line. I haven't been able to get it to work yet, but I haven't tried lately. I can try to find my notes if you want to look into it deeper. It helps to have a 3.3V Arduino (such as the Seeeduino) so you can look up directly to the pins.

**Comment by jacobrosenthal** [comment]
Wow. Thanks for quick reply. As far as I can tell it just looks like a
reset button on the reset line, and yeah level translation resistors.

Really wish theyd give up the schematic, such a pain to reverse it.

From digging in their code it looks like their setup procedure is something
like:

pinMode(reqn, OUTPUT);
digitalWrite(reqn, HIGH);
pinMode(rdy, INPUT);
Then ACI_CMD_RADIO_RESET
then ACI_CMD_WAKEUP
then send setup messages

Any reason to think your code doesnt do something similar?

**Comment by guanix** [comment]
I forgot a lot of this. I also think some of the chip's behavior changed between revisions, especially regarding what messages to send or receive when it starts up.

**Comment by jacobrosenthal** [comment]
Aha. I poked around a bit in code and since reset isnt hooked up, I needed
to manually hit the reset button when I saw Calling transmitReceive...

My output is this
Looks like its sending 26 of the 27 setup messages and getting caught up?

 Y&Hello
   Initializing
   Waiting for Standby state
   Calling transmitReceive...
   event handler
   EVENT debug=1 length=4 event=DeviceStartedEvent
   Operating mode: Setup
   Hardware error: No error
   DataCreditAvailable: 2
   sending setup message number 0
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 1
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 2
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 3
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 4
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 5
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 6
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 7
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 8
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 9
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 10
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 11
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 12
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 13
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 14
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 15
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 16
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 17
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 18
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 19
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 20
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 21
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 22
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 23
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 24
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 25
   non-success command response event: 0x1
   ready for next setup message
   event handler
   EVENT debug=1 length=3 event=CommandResponseEvent
   Status: Transaction continuation status
   Op: Setup
   sending setup message number 26

Understand if you're out of the NRF80001 game, but figured Id keep posting
my findings here for yourself or others :)

**Comment by guanix** [comment]
I have a vague recollection that one of my early versions did not wait for CommandResponseEvent confirmation of each setup message, and a later version did. If the current version does, maybe there's bug in the code that handles those confirmations so it doesn't send out the last message.

**Comment by jacobrosenthal** [comment]
OK so got it working! In the end it just took swapping out the services.h
with one I generated. Something maybe changed in newer releases or
something? Do you know where the nordic link or the nrfgo xml for that
services.h is so I can try to generate a new one that will work with the
heart monitor example?

**Comment by guanix** [comment]
I'll try to look, but I think I just used the standard heart rate monitor example in nRFgo Studio and possibly changed some oscillator settings for the board I had.

**Comment by jacobrosenthal** [comment]
Ah. Maybe oscillator settings were kicking in and the chip was going deaf?

**Comment by jacobrosenthal** [comment]
Man. Can't find a default xml for heart rate anywhere. Any chance you have
that lying around somewhere? I can set clock settings etc? I can't alter
the services.h file because it has crc I haven't figure out yet :)

**Comment by guanix** [comment]
Btw, this is only one reason why nRF51822 is so nice. No services.h or nRFgo is required.

Did you install the nRF8001 SDK? I found it in `c:\Nordic Semiconductor\nRF8001 SDK v1.5\Source_Code\projects\heart_rate_sensor`.

**Comment by jacobrosenthal** [comment]
That sounds tantalizing.

Oddly enough this sdk is locked, cant download it, even when logged in, so
thanks for bailing me out.
http://www.nordicsemi.com/chi/Products/Bluetooth-R-low-energy/nRF8001-SDK

**Comment by jacobrosenthal** [comment]
That seems to have been it, Ill push a redbear services.h example soon
here. Oddly enough its still not being seen as a heart rate monitor by the
nrf app so Ill play with that, but it is happily advertising and polling,
etc now.

**Comment by guanix** [comment]
LightBlue is an excellent iOS app for seeing exactly what's being advertised. You can check the UUIDs and such.

**Comment by jacobrosenthal** [comment]
Agreed. Just found it recently and thats what I use too :)

**Comment by jacobrosenthal** [comment]
Now it worked
I found I needed to power down after a new services.h file ...
Also helps to turn off bluetooth in order to clear out existing connections
that are cached. I think it was seeing previous characteristics or
something.
Then I re opened the nordic app and tried a connect fresh, and it worked!

**Comment by jacobrosenthal** [comment]
Support added in last push. Basically you need to use the new redbear services.h and hit the reset button on the shield after power up. Included the xml that generates the working services.h as its gotten hard to find from Nordic for some reason.

**Comment by guanix** [comment]
Good job, thanks!
