### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by rbosch** [guanix/arduino-nrf8001#3]
Hi,

I just got my nRF8001 kit and i'm trying your code. But i cant get it to work, so i have some questions. Maybe you can add that to the readme.

I have a Arduino UNIO R3, with a 3.3v switch. So i set it to 3.3v, and wire it according to your readme. The code loads fine (copied the services.h). But i can't find the shield on my iPhone. I downloaded the app from Nordic nRF Temp (when starting the .
1. Do i need to pair the device on my iPhone (should it even show up)? 
2. I can't sem to find the device either on the Master control panel (Nordic). But im not sure if it should since i didnt hookit up to the nRF Go (motherboard).
3. is there any simple way to see the device (just) works (like only power?)

OK, i found the answers myself:

There is a small error in your documentation:
# define REQN_PIN 9
# define RDYN_PIN 8

In your read-me you swapped them, maybe you can update it. Thanks for sharing, awesome!

**Comment by jacobrosenthal** [comment]
As evidenced I just havent gotten to this yet. any luck since?

**Comment by jacobrosenthal** [comment]
oh awesome let me test that. What hardware are you using?

**Comment by rbosch** [comment]
Yes, i have it working with the small pin adjustment (as described above).
