### ISSUE TITLE
Failing to setup Uno with nrf8001

### ISSUE THREAD

**Issue by proftom** [guanix/arduino-nrf8001#5]
Hello, 

I've got my an uno and a nrf8001 on a nrf2740 board (http://www.mcuol.com/download/upfile/20120105032901_nRF8001%20DK%20User%20Guide%20v1.0.pdf see page 16). It came in the nrf8001 development kit.

I cloned your repo, sorted out the libraries, renamed services.h.example to services.h and setup my arduino uno with 2 level shifting chips - one to take uno->nrf8001 from 5v to 3.3v and one to take nrf8001->uno from 3.3v to 5v.

Here is a terrible picture of it
http://gyazo.com/c8ad129ff5c8e5840533a19d714bb963
I don't use the active pin.

The problem is that I just cannot get the set-up working. It gets stuck "waiting for RDYN low indefinitely", after it reads some information from nrf8001. 

I got it to spit out the bytes it read over SPI, 

The bytes received are
debug: 3
length: 8
byte [1...8]: 3, 4, 0, 4, 0, 0, 0, 0

Am I right to expect something like
debug = 1, length =4, event = 0x81 (DeviceStartedEvent)

Here is my Serial output:

Hello
Initializing
Waiting for Standby state
Calling transmitReceive...
transmitReceive: called in polling mode
waiting for RDYN low indefinitely
Ready to transmitReceive full duplex!
event handler
EVENT debug=3 length=8 event=Unknown 3
Received message in setup but device not ready for setup
Calling transmitReceive...
transmitReceive: called in polling mode
waiting for RDYN low indefinitely

I've checked on the scope and first RDYN goes low, then REQN, then the data comes in, then REQN goes high, then RDYN goes high and never budges, but I think that is because as far as the nrf8001 is concerned, it doesn't have anything else to send.

Any ideas?
Thanks

**Comment by guanix** [comment]
Thanks, it helps a lot to see the full log.

From the Arduino's point of view, the nRF8001 is clearly sending an invalid event. That's the first problem. It would be reasonable to contact Nordic's support to ask why the chip might send such an event. Before you do that, it would be diligent to verify with a logic analyzer (or manually read the oscilloscope output) that the event being sent on the wire is actually 0x03, and not something else that is simply being misinterpreted somewhere along the way.

A different line of attack would be to send some other command that lets us verify that the device is ready for setup. For example, you could modify the setup() function to send an echo command. Or you could modify setup() to start the setup process immediately, without waiting for a valid DeviceStartedEvent, and see if that gets you anywhere.

**Comment by proftom** [comment]
I had some time and found out it was a problem with a level shifter (shifting MISO  from 3.3 to 5V). I'm not sure why running it through a level shifter should cause any problems, especially seeing as I shifted MOSI from 5 to 3. 3v. Anyway, as 3.3V is still gives logic high, I stuck that straight back into the controller and it worked :)
